// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ROr3dxmOsPWb2zyuNAFn3GLeXXO3fjs',
    appId: '1:636751256605:web:f097a37e7f7bf863603af4',
    messagingSenderId: '636751256605',
    projectId: 'edumanage-b4e53',
    authDomain: 'edumanage-b4e53.firebaseapp.com',
    storageBucket: 'edumanage-b4e53.firebasestorage.app',
    measurementId: 'G-GZJ2C1K5ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJUKrtecSZeS0CqNCvFC5-ot9OyxuOJQk',
    appId: '1:636751256605:android:8c32d46cf3bb8dd8603af4',
    messagingSenderId: '636751256605',
    projectId: 'edumanage-b4e53',
    storageBucket: 'edumanage-b4e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCeFZcwSSMIZCOK9ARjXWq6-aCHV8JuZc',
    appId: '1:636751256605:ios:0928e19bf6f9b69f603af4',
    messagingSenderId: '636751256605',
    projectId: 'edumanage-b4e53',
    storageBucket: 'edumanage-b4e53.firebasestorage.app',
    iosBundleId: 'com.example.edumanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCeFZcwSSMIZCOK9ARjXWq6-aCHV8JuZc',
    appId: '1:636751256605:ios:0928e19bf6f9b69f603af4',
    messagingSenderId: '636751256605',
    projectId: 'edumanage-b4e53',
    storageBucket: 'edumanage-b4e53.firebasestorage.app',
    iosBundleId: 'com.example.edumanage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ROr3dxmOsPWb2zyuNAFn3GLeXXO3fjs',
    appId: '1:636751256605:web:b6911028d434e992603af4',
    messagingSenderId: '636751256605',
    projectId: 'edumanage-b4e53',
    authDomain: 'edumanage-b4e53.firebaseapp.com',
    storageBucket: 'edumanage-b4e53.firebasestorage.app',
    measurementId: 'G-SNHYYVV12P',
  );
}
